name: 'Find Last Issue'
author: 'Micael Levi L. C.'
description: 'GitHub Action to find and export the number of last updated issue whithin some repository that has given labels.'
inputs:
  labels:
    description: 'Comma-separated label names that the issue must have.'
    required: true
  state:
    description: 'Issue state to filter by. Can be `"open"`, `"closed"` or `"all"`'
    required: false
outputs:
  issue_number:
    description: 'The number of the issue found, if any.'
  has_found:
    description: 'Response status. Will be `true` if some issue was found. `false` otherwise.'
  is_closed:
    description: 'Will be `true` if the found issue is closed. `false` otherwise.'
runs:
  using: 'node16'
  main: 'bundle/index.js'
branding:
  icon: 'crosshair'
  color: 'purple'
